# Generated by Django 2.2.28 on 2025-03-05 12:35

from django.db import migrations, models
import ralph.lib.mixins.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0039_merge_20241008_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBasedInformationBubble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('services', models.ManyToManyField(blank=True, related_name='information_bubbles', to='assets.Service')),
            ],
            options={
                'verbose_name': 'Service-based Information Bubble',
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
    ]
