# Generated by Django 2.2.28 on 2025-03-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('information_bubble', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebasedinformationbubble',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='information_bubbles', to='auth.Group'),
        ),
    ]
