# Generated by Django 2.2.28 on 2025-03-12 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('information_bubble', '0002_servicebasedinformationbubble_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebasedinformationbubble',
            name='groups',
        ),
        migrations.AddField(
            model_name='servicebasedinformationbubble',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='information_bubbles', to='auth.Group'),
        ),
    ]
