FROM ubuntu:focal

LABEL maintainer="Allegro.pl Sp. z o.o. opensource@allegro.pl"
LABEL authors="Allegro.pl Sp. z o.o. and Contributors opensource@allegro.pl"
LABEL description="Helper image to build deb package for Ralph."

ARG GIT_USER_NAME='root'
ARG GIT_USER_EMAIL='root@localhost'

ENV DEBIAN_FRONTEND=noninteractive
ENV SHELL=/bin/bash
ENV TERM=xterm
ENV EDITOR=nano
ENV RALPH_DIR=/opt/ralph

# The way we've pinned versions in requirement.txt files isn't compatible with chnages
# in pip's dependency resolver (pip 20.2: https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-3-2020).
# Until it's fixed on our side we need to fix to specific pip version.
# To do this we need newer version of dh-virtualenv (upgrade-pip-to option added in version 1.2).
RUN apt-get update && \
    apt-get -y install software-properties-common && \
    add-apt-repository ppa:jyrki-pulliainen/dh-virtualenv

RUN apt-get update && \
    apt-get -y install build-essential debhelper devscripts equivs dh-virtualenv \
    libmysqlclient-dev libmysqlclient21 libldap2-dev libsasl2-dev \
    libwebp-dev libbrotli-dev liblzma-dev libjpeg-dev libssl-dev libkrb5-dev \
    libcom-err2 libkeyutils-dev libxau-dev libfreetype6-dev libpcre3-dev libselinux1-dev libtinfo-dev libpng-dev \
    python3.8 python3.8-dev libffi-dev nodejs npm git-buildpackage vim-tiny git && \
    rm -rf /var/lib/apt/lists/* && \
    ldconfig && \
    ldconfig -p && \
    git config --global user.name "$GIT_USER_NAME" && \
    git config --global user.email "$GIT_USER_EMAIL"

RUN npm install -g npm@6.5.0

COPY . $RALPH_DIR

WORKDIR $RALPH_DIR
ENTRYPOINT ["make", "-f", "Makefile.docker"]
