# Generated by Django 4.0.10 on 2025-04-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0040_alter_asset_price_currency_alter_disk_base_object_and_more'),
        ('virtual', '0015_auto_20240621_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualcomponent',
            name='base_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='assets.baseobject'),
        ),
    ]
