# Generated by Django 4.0.10 on 2025-04-22 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('domains', '0009_alter_domaincontract_price_currency'),
        ('trade_marks', '0016_auto_20240621_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='business_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_business_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='design',
            name='domains',
            field=models.ManyToManyField(related_name='+', through='trade_marks.DesignsLinkedDomains', to='domains.domain'),
        ),
        migrations.AlterField(
            model_name='design',
            name='technical_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_technical_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patent',
            name='business_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_business_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patent',
            name='domains',
            field=models.ManyToManyField(related_name='+', through='trade_marks.PatentsLinkedDomains', to='domains.domain'),
        ),
        migrations.AlterField(
            model_name='patent',
            name='technical_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_technical_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='business_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_business_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='domains',
            field=models.ManyToManyField(related_name='+', through='trade_marks.TradeMarksLinkedDomains', to='domains.domain'),
        ),
        migrations.AlterField(
            model_name='trademark',
            name='technical_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_technical_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilitymodel',
            name='business_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_business_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utilitymodel',
            name='technical_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_technical_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
