# Generated by Django 2.2.28 on 2025-03-24 12:38

from django.db import migrations, models
import django.db.models.deletion
import ralph.lib.mixins.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('assets', '0039_merge_20241008_1243'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBasedVisibilityScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='name')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visibility_scopes', to='auth.Group')),
                ('services', models.ManyToManyField(blank=True, related_name='visibility_scopes', to='assets.Service')),
            ],
            options={
                'verbose_name': 'Service-based Visibility Scope',
            },
            bases=(ralph.lib.mixins.models.AdminAbsoluteUrlMixin, models.Model),
        ),
    ]
