# Generated by Django 4.0.10 on 2025-04-22 12:49

from django.db import migrations, models
import ralph.lib.mixins.fields


class Migration(migrations.Migration):

    dependencies = [
        ('deployment', '0009_auto_20240924_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prebootconfiguration',
            name='configuration',
            field=ralph.lib.mixins.fields.NUMP(models.TextField(), fields_to_ignore=('help_text', 'verbose_name')),
        ),
    ]
