# Generated by Django 2.2.28 on 2025-02-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0034_auto_20240628_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacenter',
            name='management_hostname_suffix',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='management hostname suffix'),
        ),
        migrations.AddField(
            model_name='datacenter',
            name='management_ip_prefix',
            field=models.CharField(blank=True, help_text='First 16 bits e.g. 12.345', max_length=256, null=True, verbose_name='management IP suffix'),
        ),
    ]
