# Generated by Django 2.2.28 on 2025-02-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0035_auto_20250225_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenter',
            name='management_ip_prefix',
            field=models.CharField(blank=True, help_text='First 16 bits e.g. 12.345', max_length=256, null=True, verbose_name='management IP prefix'),
        ),
    ]
