# Generated by Django 2.2.28 on 2025-03-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_center', '0036_auto_20250228_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datacenter',
            name='management_ip_prefix',
            field=models.CharField(blank=True, help_text='First 16 bits e.g. 12.34', max_length=256, null=True, verbose_name='management IP prefix'),
        ),
    ]
