# Generated by Django 4.0.10 on 2025-04-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0040_alter_asset_price_currency_alter_disk_base_object_and_more'),
        ('data_center', '0039_delete_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='base_objects',
            field=models.ManyToManyField(related_name='+', through='data_center.BaseObjectCluster', to='assets.baseobject', verbose_name='Assigned base objects'),
        ),
        migrations.AlterField(
            model_name='diskshare',
            name='base_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='assets.baseobject'),
        ),
    ]
