# Generated by Django 4.0.10 on 2025-04-22 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20250408_1522'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accessories', '0003_auto_20210607_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='user',
            field=models.ManyToManyField(related_name='+', through='accessories.AccessoryUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
