# Generated by Django 2.2.28 on 2025-03-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visibility_scope', '0001_initial'),
        ('accounts', '0010_auto_20241030_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='ralphuser',
            name='service_visibility_scopes',
            field=models.ManyToManyField(blank=True, related_name='users', to='visibility_scope.ServiceBasedVisibilityScope'),
        ),
    ]
