# Generated by Django 2.2.28 on 2025-03-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information_bubble', '0001_initial'),
        ('accounts', '0010_auto_20241030_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='ralphuser',
            name='service_information_bubbles',
            field=models.ManyToManyField(blank=True, related_name='users', to='information_bubble.ServiceBasedInformationBubble'),
        ),
    ]
