# Generated by Django 3.0.14 on 2025-04-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20250408_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ralphuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='first name'),
        ),
    ]
