# Generated by Django 3.1.14 on 2025-04-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20250409_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ralphuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
